version: '3.8'

services:
  backend:
    build:
      context: ./nba_scoreboard_api
      dockerfile: Dockerfile.prod
    container_name: "nba-scoreboard-backend"
    ports:
      - "8888:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - NBA_API_TIMEOUT=120
      - NBA_API_RETRIES=3
    dns:
      - 8.8.8.8
      - 8.8.4.4
    extra_hosts:
      - "stats.nba.com:23.56.116.63"
    networks:
      po0ww8c808co0k8skc8ooc4k: null
    labels:
      - coolify.managed=true
      - traefik.enable=true
      - traefik.http.middlewares.gzip.compress=true
      - traefik.http.routers.http-0-po0ww8c808co0k8skc8ooc4k-backend.entryPoints=http
      - traefik.http.routers.http-0-po0ww8c808co0k8skc8ooc4k-backend.middlewares=gzip
      - 'traefik.http.routers.http-0-po0ww8c808co0k8skc8ooc4k-backend.rule=Host(`h840kckc8c8swg0cos4cs4g0.143.198.70.30.sslip.io`) && PathPrefix(`/`)'
      - 'traefik.http.middlewares.nba-headers.headers.customrequestheaders.User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
      - 'traefik.http.middlewares.nba-headers.headers.customrequestheaders.Accept=application/json'

  frontend:
    build:
      context: ./NBAScoreboard
      dockerfile: Dockerfile.prod
    container_name: "nba-scoreboard-frontend"
    ports:
      - "8118:80"
    depends_on:
      - backend
    networks:
      po0ww8c808co0k8skc8ooc4k: null

networks:
  po0ww8c808co0k8skc8ooc4k:
    name: po0ww8c808co0k8skc8ooc4k
    external: true