version: '3.8'

services:
  backend:
    build:
      context: ./nba_scoreboard_api
      dockerfile: Dockerfile.prod
    container_name: "nba-scoreboard-backend"
    ports:
      - "8888:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - NBA_API_TIMEOUT=120
      - NBA_API_RETRIES=3
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - coolify-network  # Add this network
    extra_hosts:
      - "stats.nba.com:23.56.116.63"
    labels:
      - traefik.enable=true
      - traefik.docker.network=coolify-network
      - "traefik.http.routers.backend.rule=Host(`h840kckc8c8swg0cos4cs4g0.143.198.70.30.sslip.io`)"
      - traefik.http.services.backend.loadbalancer.server.port=8000
      - traefik.http.middlewares.backend-headers.headers.customrequestheaders.User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
      - traefik.http.middlewares.backend-headers.headers.customrequestheaders.Accept=application/json
      - traefik.http.middlewares.backend-headers.headers.customrequestheaders.Accept-Language=en-US,en;q=0.9
      - traefik.http.middlewares.backend-headers.headers.customrequestheaders.Origin=https://stats.nba.com
      - traefik.http.middlewares.backend-headers.headers.customrequestheaders.Referer=https://stats.nba.com

  frontend:
    # ... frontend config remains the same
    networks:
      - coolify-network

networks:
  coolify-network:
    external: true
    name: coolify-proxy-network