version: '3.8'
services:
  frontend:
    build:
      context: ./NBAScoreboard
      dockerfile: Dockerfile.prod
    ports:
      - '80:80'
    environment:
      - 'VITE_API_URL=${API_URL:-http://backend:8000}'
    depends_on:
      - backend
    networks:
      - app_network
  backend:
    build:
      context: ./nba_scoreboard_api
      dockerfile: Dockerfile.prod
    ports:
      - '8000:8000'
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - 'CORS_ORIGINS=${FRONTEND_URL:-http://localhost:80}'
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
