# docker-compose.yml
version: '3.8'

services:
  frontend:
    build:
      context: ./NBAScoreboard
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=${API_URL:-http://backend:8000}
    depends_on:
      - backend

  backend:
    build:
      context: ./nba_scoreboard_api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000

networks:
  default:
    driver: bridge
