# docker-compose.prod.yml
version: '3.8'

services:
  backend:
    build:
      context: ./nba_scoreboard_api
      dockerfile: Dockerfile
    # If your backend is serving on 8000
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./NBAScoreboard
      dockerfile: Dockerfile
    # We'll expose port 80 from the NGINX container (or serve)
    ports:
      - "80:80"
    depends_on:
      - backend
