# docker-compose.prod.yml
version: '3.8'

services:
  backend:
    build:
      context: ./nba_scoreboard_api
      dockerfile: Dockerfile.prod
    container_name: "nba-scoreboard-backend"
    ports:
      - "8888:8000"
    environment:
      # If your code uses environment variables, define them here.
      # For example:
      # HOST=0.0.0.0
      # PORT=8000
      # ...
      - HOST=0.0.0.0
      - PORT=8000

  frontend:
    build:
      context: ./NBAScoreboard
      dockerfile: Dockerfile.prod
    container_name: "nba-scoreboard-frontend"
    ports:
      - "80:80"
    # The React container has an Nginx reverse proxy configured via nginx.conf
    # to route /api -> http://backend:8000
    depends_on:
      - backend
