services:
  nba_scoreboard:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
      - "3001:3000"
    environment:
      - API_URL=https://api.server.nbaapi.com
      - FRONTEND_URL=https://scoreboard.server.nbaapi.com