# docker-compose.yml
version: '3.8'

services:
  frontend:
    build:
      context: ./NBAScoreboard
      dockerfile: Dockerfile
    ports:
      - "3000"
    environment:
      - VITE_API_URL=${API_URL:-http://backend:8080}
      - NODE_ENV=production
    depends_on:
      - backend

  backend:
    build:
      context: ./nba_scoreboard_api
      dockerfile: Dockerfile
    ports:
      - "8080"
    environment:
      - HOST=0.0.0.0
      - PORT=8080

networks:
  default:
    driver: bridge
