# docker-compose.yml
version: '3.8'

services:
  frontend:
    build:
      context: ./NBAScoreboard
      dockerfile: Dockerfile
      no_cache: true
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:8000
    depends_on:
      - backend
    volumes:
      - ./NBAScoreboard:/app
      - /app/node_modules

  backend:
    build:
      context: ./nba_scoreboard_api
      dockerfile: Dockerfile
      no_cache: true
    ports:
      - "8000:8000"
    volumes:
      - ./nba_scoreboard_api:/app

networks:
  default:
    driver: bridge