version: '3.8'

services:
  frontend:
    build:
      context: ./NBAScoreboard
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=production
      - VITE_API_URL=${API_URL}
    labels:
      - coolify.managed=true
      - traefik.enable=true
      - traefik.http.middlewares.gzip.compress=true
    networks:
      - app_network
    restart: unless-stopped

  backend:
    build:
      context: ./nba_scoreboard_api
      dockerfile: Dockerfile.prod
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - CORS_ORIGINS=${FRONTEND_URL}
    expose:
      - "8000"
    labels:
      - coolify.managed=true
      - traefik.enable=true
      - traefik.http.middlewares.gzip.compress=true
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge